// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Title                *string  `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	Body                 *string  `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	UserId               *uint64  `protobuf:"varint,3,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Id                   *uint64  `protobuf:"varint,4,req,name=id" json:"id,omitempty"`
	Timestamp            *int64   `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Likes                *int64   `protobuf:"varint,6,opt,name=likes" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Post) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Post) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Post) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Post) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

type IndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

type SearchQuery struct {
	Term                 *string  `protobuf:"bytes,1,req,name=term" json:"term,omitempty"`
	Total                *uint64  `protobuf:"varint,2,req,name=total" json:"total,omitempty"`
	From                 *uint64  `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchQuery) Reset()         { *m = SearchQuery{} }
func (m *SearchQuery) String() string { return proto.CompactTextString(m) }
func (*SearchQuery) ProtoMessage()    {}
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *SearchQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchQuery.Unmarshal(m, b)
}
func (m *SearchQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchQuery.Marshal(b, m, deterministic)
}
func (m *SearchQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchQuery.Merge(m, src)
}
func (m *SearchQuery) XXX_Size() int {
	return xxx_messageInfo_SearchQuery.Size(m)
}
func (m *SearchQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SearchQuery proto.InternalMessageInfo

func (m *SearchQuery) GetTerm() string {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return ""
}

func (m *SearchQuery) GetTotal() uint64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *SearchQuery) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

type SearchResult struct {
	Id                   []uint64 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetId() []uint64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type Likes struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Likes                *int64   `protobuf:"varint,2,req,name=likes" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Likes) Reset()         { *m = Likes{} }
func (m *Likes) String() string { return proto.CompactTextString(m) }
func (*Likes) ProtoMessage()    {}
func (*Likes) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *Likes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Likes.Unmarshal(m, b)
}
func (m *Likes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Likes.Marshal(b, m, deterministic)
}
func (m *Likes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Likes.Merge(m, src)
}
func (m *Likes) XXX_Size() int {
	return xxx_messageInfo_Likes.Size(m)
}
func (m *Likes) XXX_DiscardUnknown() {
	xxx_messageInfo_Likes.DiscardUnknown(m)
}

var xxx_messageInfo_Likes proto.InternalMessageInfo

func (m *Likes) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Likes) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

type LikesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikesResponse) Reset()         { *m = LikesResponse{} }
func (m *LikesResponse) String() string { return proto.CompactTextString(m) }
func (*LikesResponse) ProtoMessage()    {}
func (*LikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *LikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikesResponse.Unmarshal(m, b)
}
func (m *LikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikesResponse.Marshal(b, m, deterministic)
}
func (m *LikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesResponse.Merge(m, src)
}
func (m *LikesResponse) XXX_Size() int {
	return xxx_messageInfo_LikesResponse.Size(m)
}
func (m *LikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikesResponse proto.InternalMessageInfo

type Id struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{6}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type DeletePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{7}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

type Timestamp struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Timestamp            *int64   `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{8}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Timestamp) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type SetTimestampResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTimestampResponse) Reset()         { *m = SetTimestampResponse{} }
func (m *SetTimestampResponse) String() string { return proto.CompactTextString(m) }
func (*SetTimestampResponse) ProtoMessage()    {}
func (*SetTimestampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{9}
}

func (m *SetTimestampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTimestampResponse.Unmarshal(m, b)
}
func (m *SetTimestampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTimestampResponse.Marshal(b, m, deterministic)
}
func (m *SetTimestampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTimestampResponse.Merge(m, src)
}
func (m *SetTimestampResponse) XXX_Size() int {
	return xxx_messageInfo_SetTimestampResponse.Size(m)
}
func (m *SetTimestampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTimestampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTimestampResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*IndexResponse)(nil), "IndexResponse")
	proto.RegisterType((*SearchQuery)(nil), "SearchQuery")
	proto.RegisterType((*SearchResult)(nil), "SearchResult")
	proto.RegisterType((*Likes)(nil), "Likes")
	proto.RegisterType((*LikesResponse)(nil), "LikesResponse")
	proto.RegisterType((*Id)(nil), "Id")
	proto.RegisterType((*DeletePostResponse)(nil), "DeletePostResponse")
	proto.RegisterType((*Timestamp)(nil), "Timestamp")
	proto.RegisterType((*SetTimestampResponse)(nil), "SetTimestampResponse")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e) }

var fileDescriptor_453745cff914010e = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x85, 0xf3, 0x7f, 0x6f, 0x87, 0xb6, 0x48, 0x43, 0x80, 0x28, 0x42, 0x28, 0xb2, 0x90, 0xc8,
	0x06, 0x2f, 0x60, 0xc5, 0x9e, 0x4d, 0x05, 0x0b, 0x48, 0xd9, 0xa3, 0x42, 0x06, 0x11, 0x91, 0x34,
	0x55, 0xec, 0x4a, 0xf4, 0x21, 0x78, 0x3f, 0x1e, 0x07, 0xd9, 0x6e, 0x9d, 0x16, 0x75, 0x95, 0x99,
	0xf1, 0xd8, 0xe7, 0x3b, 0x27, 0x30, 0x14, 0x34, 0xeb, 0xde, 0x3e, 0xf8, 0xa2, 0x6b, 0x65, 0xcb,
	0xbe, 0x5d, 0x08, 0x1e, 0x5b, 0x21, 0x31, 0x86, 0x50, 0x56, 0xb2, 0xa6, 0xc4, 0xcd, 0xbc, 0x7c,
	0x50, 0x98, 0x06, 0x11, 0x82, 0xd7, 0xb6, 0x5c, 0x25, 0x9e, 0x1e, 0xea, 0x1a, 0x4f, 0xe1, 0xdf,
	0x52, 0x50, 0xf7, 0x52, 0x95, 0x89, 0x9f, 0x79, 0x79, 0x50, 0x44, 0xaa, 0x9d, 0x94, 0x38, 0x06,
	0xaf, 0x2a, 0x93, 0x40, 0xcf, 0xbc, 0xaa, 0xc4, 0x33, 0x18, 0xc8, 0xaa, 0x21, 0x21, 0x67, 0xcd,
	0x22, 0x09, 0x33, 0x37, 0xf7, 0x8b, 0x7e, 0xa0, 0x04, 0xeb, 0xea, 0x93, 0x44, 0x12, 0xe9, 0x13,
	0xd3, 0xb0, 0x43, 0x18, 0x4d, 0xe6, 0x25, 0x7d, 0x15, 0x24, 0x16, 0xed, 0x5c, 0x10, 0xbb, 0x87,
	0x83, 0xa9, 0x06, 0x7e, 0x5a, 0x52, 0xb7, 0x52, 0x40, 0x92, 0xba, 0x66, 0x4d, 0xa9, 0x6b, 0x8d,
	0xde, 0xca, 0x59, 0xad, 0x29, 0x83, 0xc2, 0x34, 0x6a, 0xf3, 0xbd, 0x6b, 0x9b, 0xc4, 0xcf, 0xdc,
	0x3c, 0x28, 0x74, 0xcd, 0xce, 0x61, 0x68, 0x1e, 0x2b, 0x48, 0x2c, 0x6b, 0xb9, 0x26, 0x76, 0x33,
	0xdf, 0x10, 0xb3, 0x2b, 0x08, 0x1f, 0x14, 0x86, 0x3d, 0xd8, 0x58, 0xb1, 0xb0, 0x4a, 0x62, 0x1b,
	0x56, 0xaf, 0x5b, 0xd8, 0x18, 0x3c, 0x9b, 0x83, 0xbd, 0xcc, 0x62, 0xc0, 0x3b, 0xaa, 0x49, 0x92,
	0x0a, 0xda, 0xee, 0xde, 0xc2, 0xe0, 0xd9, 0x86, 0xf1, 0x57, 0x6f, 0x27, 0x3a, 0xa3, 0xd9, 0x0f,
	0xd8, 0x09, 0xc4, 0x53, 0x92, 0xf6, 0xf6, 0xe6, 0xc9, 0xeb, 0x1f, 0x17, 0x22, 0xe3, 0x0f, 0x33,
	0x08, 0x75, 0x8e, 0x18, 0x72, 0xa5, 0x9a, 0x8e, 0xf9, 0x6e, 0xac, 0x0e, 0x5e, 0xda, 0xdd, 0x21,
	0xdf, 0x4a, 0x38, 0x1d, 0xf1, 0xed, 0x88, 0x98, 0x83, 0x17, 0xf0, 0x7f, 0x4a, 0xd2, 0xe4, 0x12,
	0x71, 0xfd, 0x4d, 0xc7, 0x7c, 0xd7, 0xb8, 0x83, 0x39, 0x40, 0x6f, 0x12, 0x7d, 0x3e, 0x29, 0xd3,
	0x23, 0xbe, 0xc7, 0xb6, 0x83, 0x37, 0xea, 0x27, 0xf4, 0xf4, 0x08, 0xdc, 0xd6, 0xe9, 0x31, 0xdf,
	0x67, 0x8c, 0x39, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x67, 0x04, 0x7e, 0xb6, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	Index(ctx context.Context, in *Post, opts ...grpc.CallOption) (*IndexResponse, error)
	Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (*SearchResult, error)
	SetLikes(ctx context.Context, in *Likes, opts ...grpc.CallOption) (*LikesResponse, error)
	DeletePost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*DeletePostResponse, error)
	SetTimestamp(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*SetTimestampResponse, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Index(ctx context.Context, in *Post, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/Search/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) Search(ctx context.Context, in *SearchQuery, opts ...grpc.CallOption) (*SearchResult, error) {
	out := new(SearchResult)
	err := c.cc.Invoke(ctx, "/Search/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SetLikes(ctx context.Context, in *Likes, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/Search/SetLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) DeletePost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/Search/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SetTimestamp(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (*SetTimestampResponse, error) {
	out := new(SetTimestampResponse)
	err := c.cc.Invoke(ctx, "/Search/SetTimestamp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	Index(context.Context, *Post) (*IndexResponse, error)
	Search(context.Context, *SearchQuery) (*SearchResult, error)
	SetLikes(context.Context, *Likes) (*LikesResponse, error)
	DeletePost(context.Context, *Id) (*DeletePostResponse, error)
	SetTimestamp(context.Context, *Timestamp) (*SetTimestampResponse, error)
}

// UnimplementedSearchServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (*UnimplementedSearchServer) Index(ctx context.Context, req *Post) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (*UnimplementedSearchServer) Search(ctx context.Context, req *SearchQuery) (*SearchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedSearchServer) SetLikes(ctx context.Context, req *Likes) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLikes not implemented")
}
func (*UnimplementedSearchServer) DeletePost(ctx context.Context, req *Id) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedSearchServer) SetTimestamp(ctx context.Context, req *Timestamp) (*SetTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTimestamp not implemented")
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Search/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Index(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Search/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Search(ctx, req.(*SearchQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SetLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Likes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SetLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Search/SetLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SetLikes(ctx, req.(*Likes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Search/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).DeletePost(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SetTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SetTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Search/SetTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SetTimestamp(ctx, req.(*Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _Search_Index_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Search_Search_Handler,
		},
		{
			MethodName: "SetLikes",
			Handler:    _Search_SetLikes_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Search_DeletePost_Handler,
		},
		{
			MethodName: "SetTimestamp",
			Handler:    _Search_SetTimestamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
