// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts-read.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Id struct {
	Uint64               *Id      `protobuf:"bytes,1,req,name=uint64" json:"uint64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{0}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetUint64() *Id {
	if m != nil {
		return m.Uint64
	}
	return nil
}

type Post struct {
	Id                   *uint64    `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	UserId               *uint64    `protobuf:"varint,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Title                *string    `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Body                 *string    `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	Likes                *int64     `protobuf:"varint,5,opt,name=likes" json:"likes,omitempty"`
	CreatedAt            *int64     `protobuf:"varint,6,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            *int64     `protobuf:"varint,7,req,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Comments             []*Comment `protobuf:"bytes,8,rep,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Post) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Post) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

func (m *Post) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Post) GetUpdatedAt() int64 {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return 0
}

func (m *Post) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Comment struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PostId               *uint64  `protobuf:"varint,2,req,name=post_id,json=postId" json:"post_id,omitempty"`
	ParentId             *uint64  `protobuf:"varint,3,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	UserId               *uint64  `protobuf:"varint,4,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Body                 *string  `protobuf:"bytes,5,req,name=body" json:"body,omitempty"`
	CreatedAt            *uint64  `protobuf:"varint,6,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Likes                *int64   `protobuf:"varint,7,opt,name=Likes" json:"Likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{2}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Comment) GetPostId() uint64 {
	if m != nil && m.PostId != nil {
		return *m.PostId
	}
	return 0
}

func (m *Comment) GetParentId() uint64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

func (m *Comment) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Comment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Comment) GetCreatedAt() uint64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Comment) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

type MultiplePosts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplePosts) Reset()         { *m = MultiplePosts{} }
func (m *MultiplePosts) String() string { return proto.CompactTextString(m) }
func (*MultiplePosts) ProtoMessage()    {}
func (*MultiplePosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{3}
}

func (m *MultiplePosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplePosts.Unmarshal(m, b)
}
func (m *MultiplePosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplePosts.Marshal(b, m, deterministic)
}
func (m *MultiplePosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplePosts.Merge(m, src)
}
func (m *MultiplePosts) XXX_Size() int {
	return xxx_messageInfo_MultiplePosts.Size(m)
}
func (m *MultiplePosts) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplePosts.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplePosts proto.InternalMessageInfo

func (m *MultiplePosts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GetPostsQuery struct {
	Total                *uint64  `protobuf:"varint,1,req,name=total" json:"total,omitempty"`
	From                 *uint64  `protobuf:"varint,2,opt,name=from" json:"from,omitempty"`
	UserId               *uint64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Sort                 *string  `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsQuery) Reset()         { *m = GetPostsQuery{} }
func (m *GetPostsQuery) String() string { return proto.CompactTextString(m) }
func (*GetPostsQuery) ProtoMessage()    {}
func (*GetPostsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{4}
}

func (m *GetPostsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsQuery.Unmarshal(m, b)
}
func (m *GetPostsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsQuery.Marshal(b, m, deterministic)
}
func (m *GetPostsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsQuery.Merge(m, src)
}
func (m *GetPostsQuery) XXX_Size() int {
	return xxx_messageInfo_GetPostsQuery.Size(m)
}
func (m *GetPostsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsQuery proto.InternalMessageInfo

func (m *GetPostsQuery) GetTotal() uint64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *GetPostsQuery) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *GetPostsQuery) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *GetPostsQuery) GetSort() string {
	if m != nil && m.Sort != nil {
		return *m.Sort
	}
	return ""
}

type Ids struct {
	Id                   []uint64 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{5}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetId() []uint64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "Id")
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*Comment)(nil), "Comment")
	proto.RegisterType((*MultiplePosts)(nil), "MultiplePosts")
	proto.RegisterType((*GetPostsQuery)(nil), "GetPostsQuery")
	proto.RegisterType((*Ids)(nil), "Ids")
}

func init() { proto.RegisterFile("posts-read.proto", fileDescriptor_753a14ea5b614494) }

var fileDescriptor_753a14ea5b614494 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6a, 0xdc, 0x30,
	0x10, 0xc6, 0xe3, 0x7f, 0xbb, 0xf6, 0x6c, 0xb3, 0x14, 0x91, 0x52, 0x91, 0x50, 0x70, 0x45, 0x29,
	0x3e, 0xa4, 0x3e, 0x2c, 0xa5, 0xf7, 0xb4, 0xd0, 0x60, 0x68, 0xa1, 0xd5, 0x0b, 0x04, 0x37, 0x52,
	0xc0, 0xd4, 0xbb, 0x32, 0xd2, 0xf8, 0x90, 0x4b, 0xdf, 0xa9, 0xcf, 0xd2, 0x17, 0x2a, 0x1a, 0xd9,
	0x61, 0xcd, 0xe6, 0x36, 0xdf, 0x37, 0x03, 0x9a, 0xdf, 0x37, 0x82, 0x97, 0x83, 0x71, 0xe8, 0x3e,
	0x58, 0xdd, 0xaa, 0x7a, 0xb0, 0x06, 0x8d, 0x78, 0x0b, 0x71, 0xa3, 0xd8, 0x15, 0xac, 0xc6, 0xee,
	0x80, 0x9f, 0x3e, 0xf2, 0xa8, 0x8c, 0xab, 0xcd, 0x2e, 0xa9, 0x1b, 0x25, 0x27, 0x4b, 0xfc, 0x8b,
	0x20, 0xfd, 0x61, 0x1c, 0xb2, 0x2d, 0xc4, 0x9d, 0xa2, 0x89, 0x54, 0xc6, 0x9d, 0x62, 0xaf, 0x61,
	0x3d, 0x3a, 0x6d, 0xef, 0x3a, 0xc5, 0x63, 0x32, 0x57, 0x5e, 0x36, 0x8a, 0x5d, 0x40, 0x86, 0x1d,
	0xf6, 0x9a, 0x27, 0x65, 0x5c, 0x15, 0x32, 0x08, 0xc6, 0x20, 0xfd, 0x65, 0xd4, 0x23, 0x4f, 0xcb,
	0xa8, 0x2a, 0x24, 0xd5, 0x7e, 0xb2, 0xef, 0x7e, 0x6b, 0xc7, 0xb3, 0x32, 0xaa, 0x12, 0x19, 0x04,
	0x7b, 0x03, 0x70, 0x6f, 0x75, 0x8b, 0x5a, 0xdd, 0xb5, 0xc8, 0x57, 0x65, 0x5c, 0x25, 0xb2, 0x98,
	0x9c, 0x1b, 0xf4, 0xed, 0x71, 0x50, 0x73, 0x7b, 0x1d, 0xda, 0x93, 0x73, 0x83, 0xec, 0x1d, 0xe4,
	0xf7, 0x66, 0xbf, 0xd7, 0x07, 0x74, 0x3c, 0x2f, 0x93, 0x6a, 0xb3, 0xcb, 0xeb, 0x2f, 0xc1, 0x90,
	0x4f, 0x1d, 0xf1, 0x37, 0x82, 0xf5, 0xe4, 0x3e, 0x07, 0xe6, 0x83, 0x3a, 0x02, 0xf3, 0x92, 0x72,
	0x2a, 0x86, 0xd6, 0xea, 0x03, 0xb5, 0x92, 0x32, 0xaa, 0x52, 0x99, 0x07, 0xa3, 0x59, 0xc4, 0x91,
	0x2e, 0xe2, 0x98, 0xc1, 0x33, 0x4a, 0x23, 0x80, 0x9f, 0x22, 0xa6, 0xc7, 0x88, 0x17, 0x90, 0x7d,
	0xa3, 0x5c, 0xd6, 0x21, 0x17, 0x12, 0xe2, 0x1a, 0xce, 0xbf, 0x8f, 0x3d, 0x76, 0x43, 0xaf, 0xfd,
	0x41, 0x1c, 0xbb, 0x82, 0x8c, 0x2e, 0xca, 0x23, 0xe2, 0xcc, 0x6a, 0x6f, 0xcb, 0xe0, 0x89, 0x07,
	0x38, 0xbf, 0xd5, 0x48, 0x83, 0x3f, 0x47, 0x6d, 0x29, 0x6c, 0x34, 0xd8, 0xf6, 0x13, 0x69, 0x10,
	0x7e, 0xbb, 0x07, 0x6b, 0xf6, 0x3c, 0x26, 0x1c, 0xaa, 0x8f, 0x51, 0x02, 0xe5, 0x11, 0x8a, 0x33,
	0x16, 0xe7, 0x1b, 0xfa, 0x5a, 0xbc, 0x82, 0xa4, 0x51, 0xee, 0x29, 0xc4, 0x24, 0x84, 0xb8, 0xfb,
	0x03, 0x05, 0xbd, 0x2d, 0x75, 0xeb, 0x83, 0xdb, 0xdc, 0x6a, 0xfc, 0x3a, 0xf6, 0x3d, 0xfd, 0x24,
	0xff, 0xbf, 0x2e, 0xc3, 0xb6, 0xe2, 0x8c, 0x5d, 0x43, 0x3e, 0x2f, 0xca, 0xb6, 0xf5, 0x62, 0xe7,
	0xcb, 0x6d, 0xbd, 0x20, 0x16, 0x67, 0xec, 0x3d, 0xbc, 0x98, 0x47, 0x3e, 0x3f, 0x36, 0x8a, 0xa5,
	0x75, 0xa3, 0xdc, 0xe9, 0xdc, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xc6, 0xd9, 0x80, 0xec,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsReadClient is the client API for PostsRead service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsReadClient interface {
	GetFullPost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Post, error)
	GetPosts(ctx context.Context, in *GetPostsQuery, opts ...grpc.CallOption) (*MultiplePosts, error)
	GetPostsById(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*MultiplePosts, error)
}

type postsReadClient struct {
	cc *grpc.ClientConn
}

func NewPostsReadClient(cc *grpc.ClientConn) PostsReadClient {
	return &postsReadClient{cc}
}

func (c *postsReadClient) GetFullPost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/PostsRead/GetFullPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsReadClient) GetPosts(ctx context.Context, in *GetPostsQuery, opts ...grpc.CallOption) (*MultiplePosts, error) {
	out := new(MultiplePosts)
	err := c.cc.Invoke(ctx, "/PostsRead/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsReadClient) GetPostsById(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*MultiplePosts, error) {
	out := new(MultiplePosts)
	err := c.cc.Invoke(ctx, "/PostsRead/GetPostsById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsReadServer is the server API for PostsRead service.
type PostsReadServer interface {
	GetFullPost(context.Context, *Id) (*Post, error)
	GetPosts(context.Context, *GetPostsQuery) (*MultiplePosts, error)
	GetPostsById(context.Context, *Ids) (*MultiplePosts, error)
}

// UnimplementedPostsReadServer can be embedded to have forward compatible implementations.
type UnimplementedPostsReadServer struct {
}

func (*UnimplementedPostsReadServer) GetFullPost(ctx context.Context, req *Id) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullPost not implemented")
}
func (*UnimplementedPostsReadServer) GetPosts(ctx context.Context, req *GetPostsQuery) (*MultiplePosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedPostsReadServer) GetPostsById(ctx context.Context, req *Ids) (*MultiplePosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostsById not implemented")
}

func RegisterPostsReadServer(s *grpc.Server, srv PostsReadServer) {
	s.RegisterService(&_PostsRead_serviceDesc, srv)
}

func _PostsRead_GetFullPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetFullPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostsRead/GetFullPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetFullPost(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsRead_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostsRead/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetPosts(ctx, req.(*GetPostsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsRead_GetPostsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetPostsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostsRead/GetPostsById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetPostsById(ctx, req.(*Ids))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsRead_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostsRead",
	HandlerType: (*PostsReadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullPost",
			Handler:    _PostsRead_GetFullPost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _PostsRead_GetPosts_Handler,
		},
		{
			MethodName: "GetPostsById",
			Handler:    _PostsRead_GetPostsById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts-read.proto",
}
