// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts-read.proto

package postsread

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (x *HealthCheckResponse_ServingStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HealthCheckResponse_ServingStatus_value, data, "HealthCheckResponse_ServingStatus")
	if err != nil {
		return err
	}
	*x = HealthCheckResponse_ServingStatus(value)
	return nil
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{7, 0}
}

type Id struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{0}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type Post struct {
	Id                   *uint64    `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	UserId               *uint64    `protobuf:"varint,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Title                *string    `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	Body                 *string    `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	Likes                *int64     `protobuf:"varint,5,opt,name=likes" json:"likes,omitempty"`
	CreatedAt            *int64     `protobuf:"varint,6,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            *int64     `protobuf:"varint,7,req,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Comments             []*Comment `protobuf:"bytes,8,rep,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{1}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Post) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Post) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

func (m *Post) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Post) GetUpdatedAt() int64 {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return 0
}

func (m *Post) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Comment struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	PostId               *uint64  `protobuf:"varint,2,req,name=post_id,json=postId" json:"post_id,omitempty"`
	ParentId             *uint64  `protobuf:"varint,3,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	UserId               *uint64  `protobuf:"varint,4,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Body                 *string  `protobuf:"bytes,5,req,name=body" json:"body,omitempty"`
	CreatedAt            *int64   `protobuf:"varint,6,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Likes                *int64   `protobuf:"varint,7,opt,name=Likes" json:"Likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{2}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Comment) GetPostId() uint64 {
	if m != nil && m.PostId != nil {
		return *m.PostId
	}
	return 0
}

func (m *Comment) GetParentId() uint64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

func (m *Comment) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Comment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Comment) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Comment) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

type MultiplePosts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplePosts) Reset()         { *m = MultiplePosts{} }
func (m *MultiplePosts) String() string { return proto.CompactTextString(m) }
func (*MultiplePosts) ProtoMessage()    {}
func (*MultiplePosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{3}
}

func (m *MultiplePosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplePosts.Unmarshal(m, b)
}
func (m *MultiplePosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplePosts.Marshal(b, m, deterministic)
}
func (m *MultiplePosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplePosts.Merge(m, src)
}
func (m *MultiplePosts) XXX_Size() int {
	return xxx_messageInfo_MultiplePosts.Size(m)
}
func (m *MultiplePosts) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplePosts.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplePosts proto.InternalMessageInfo

func (m *MultiplePosts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GetPostsQuery struct {
	Total                *uint64  `protobuf:"varint,1,req,name=total" json:"total,omitempty"`
	From                 *uint64  `protobuf:"varint,2,opt,name=from" json:"from,omitempty"`
	UserId               *uint64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Sort                 *string  `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsQuery) Reset()         { *m = GetPostsQuery{} }
func (m *GetPostsQuery) String() string { return proto.CompactTextString(m) }
func (*GetPostsQuery) ProtoMessage()    {}
func (*GetPostsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{4}
}

func (m *GetPostsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsQuery.Unmarshal(m, b)
}
func (m *GetPostsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsQuery.Marshal(b, m, deterministic)
}
func (m *GetPostsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsQuery.Merge(m, src)
}
func (m *GetPostsQuery) XXX_Size() int {
	return xxx_messageInfo_GetPostsQuery.Size(m)
}
func (m *GetPostsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsQuery proto.InternalMessageInfo

func (m *GetPostsQuery) GetTotal() uint64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *GetPostsQuery) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *GetPostsQuery) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *GetPostsQuery) GetSort() string {
	if m != nil && m.Sort != nil {
		return *m.Sort
	}
	return ""
}

type Ids struct {
	Id                   []uint64 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ids) Reset()         { *m = Ids{} }
func (m *Ids) String() string { return proto.CompactTextString(m) }
func (*Ids) ProtoMessage()    {}
func (*Ids) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{5}
}

func (m *Ids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ids.Unmarshal(m, b)
}
func (m *Ids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ids.Marshal(b, m, deterministic)
}
func (m *Ids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ids.Merge(m, src)
}
func (m *Ids) XXX_Size() int {
	return xxx_messageInfo_Ids.Size(m)
}
func (m *Ids) XXX_DiscardUnknown() {
	xxx_messageInfo_Ids.DiscardUnknown(m)
}

var xxx_messageInfo_Ids proto.InternalMessageInfo

func (m *Ids) GetId() []uint64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{6}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	Status               *HealthCheckResponse_ServingStatus `protobuf:"varint,1,req,name=status,enum=postsread.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_753a14ea5b614494, []int{7}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("postsread.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Id)(nil), "postsread.Id")
	proto.RegisterType((*Post)(nil), "postsread.Post")
	proto.RegisterType((*Comment)(nil), "postsread.Comment")
	proto.RegisterType((*MultiplePosts)(nil), "postsread.MultiplePosts")
	proto.RegisterType((*GetPostsQuery)(nil), "postsread.GetPostsQuery")
	proto.RegisterType((*Ids)(nil), "postsread.Ids")
	proto.RegisterType((*HealthCheckRequest)(nil), "postsread.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "postsread.HealthCheckResponse")
}

func init() { proto.RegisterFile("posts-read.proto", fileDescriptor_753a14ea5b614494) }

var fileDescriptor_753a14ea5b614494 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf1, 0xbf, 0x26, 0x9e, 0x90, 0x36, 0x5a, 0x82, 0xb0, 0x82, 0x8a, 0x2c, 0x4b, 0x48,
	0x3e, 0xd0, 0x1c, 0x72, 0x40, 0x88, 0x03, 0x52, 0x29, 0x34, 0x58, 0x40, 0x0a, 0x1b, 0xfe, 0x1c,
	0x23, 0x93, 0xdd, 0x52, 0xab, 0x4e, 0xd6, 0x78, 0xc7, 0x48, 0x7d, 0x12, 0x9e, 0x83, 0x07, 0xe2,
	0x4d, 0x38, 0xa0, 0xdd, 0xb5, 0x23, 0x1b, 0x95, 0x72, 0xb1, 0x76, 0xbe, 0x6f, 0x46, 0xde, 0xef,
	0x37, 0x5a, 0x18, 0x15, 0x42, 0xa2, 0x3c, 0x2a, 0x79, 0xca, 0xa6, 0x45, 0x29, 0x50, 0x10, 0x5f,
	0x2b, 0x4a, 0x88, 0xc6, 0x60, 0x27, 0x8c, 0xec, 0xab, 0x6f, 0x60, 0x85, 0x76, 0xec, 0x52, 0x3b,
	0x61, 0xd1, 0x2f, 0x0b, 0xdc, 0x77, 0x42, 0xa2, 0x32, 0xb2, 0x9d, 0x91, 0x31, 0x72, 0x0f, 0x7a,
	0x95, 0xe4, 0xe5, 0x2a, 0x63, 0x81, 0xad, 0xc5, 0x3d, 0x55, 0x26, 0x8c, 0x8c, 0xc1, 0xc3, 0x0c,
	0x73, 0x1e, 0x38, 0xa1, 0x1d, 0xfb, 0xd4, 0x14, 0x84, 0x80, 0xfb, 0x45, 0xb0, 0xab, 0xc0, 0x0d,
	0xad, 0xd8, 0xa7, 0xfa, 0xac, 0x3a, 0xf3, 0xec, 0x92, 0xcb, 0xc0, 0x0b, 0xad, 0xd8, 0xa1, 0xa6,
	0x20, 0x87, 0x00, 0xeb, 0x92, 0xa7, 0xc8, 0xd9, 0x2a, 0xc5, 0x60, 0x2f, 0xb4, 0x63, 0x87, 0xfa,
	0xb5, 0x72, 0x8c, 0xca, 0xae, 0x0a, 0xd6, 0xd8, 0x3d, 0x63, 0xd7, 0xca, 0x31, 0x92, 0x29, 0xf4,
	0xd7, 0x62, 0xb3, 0xe1, 0x5b, 0x94, 0x41, 0x3f, 0x74, 0xe2, 0xc1, 0x8c, 0x4c, 0x77, 0x19, 0xa7,
	0x27, 0xc6, 0xa2, 0xbb, 0x9e, 0xe8, 0xa7, 0x05, 0xbd, 0x5a, 0xbd, 0x2e, 0xa2, 0x1a, 0x6d, 0x45,
	0x54, 0x65, 0xc2, 0xc8, 0x7d, 0xf0, 0x8b, 0xb4, 0xe4, 0x5b, 0x6d, 0x39, 0xa1, 0x15, 0xbb, 0xb4,
	0x6f, 0x84, 0xa4, 0x03, 0xc6, 0xed, 0x80, 0x69, 0x10, 0x78, 0x9a, 0x8b, 0x41, 0xf0, 0x9f, 0xb0,
	0x63, 0xf0, 0xde, 0x68, 0x42, 0x3d, 0x43, 0x48, 0x17, 0xd1, 0x63, 0x18, 0xbe, 0xad, 0x72, 0xcc,
	0x8a, 0x9c, 0xab, 0xd5, 0x48, 0xf2, 0x10, 0x3c, 0x9d, 0x31, 0xb0, 0x74, 0xe2, 0x83, 0x56, 0x62,
	0xd5, 0x40, 0x8d, 0x1b, 0x9d, 0xc3, 0x70, 0xce, 0x51, 0x8f, 0xbc, 0xaf, 0x78, 0xa9, 0x17, 0x80,
	0x02, 0xd3, 0xbc, 0xce, 0x6c, 0x0a, 0x75, 0xcf, 0xf3, 0x52, 0x6c, 0x02, 0x5b, 0x07, 0xd3, 0xe7,
	0x76, 0x28, 0x93, 0xb7, 0x15, 0x4a, 0x8a, 0x12, 0x9b, 0xbd, 0xaa, 0x73, 0x74, 0x17, 0x9c, 0x84,
	0xc9, 0x1d, 0x4e, 0xc7, 0xe0, 0x8c, 0xc6, 0x40, 0x5e, 0xf1, 0x34, 0xc7, 0x8b, 0x93, 0x0b, 0xbe,
	0xbe, 0xa4, 0xfc, 0x5b, 0xc5, 0x25, 0x46, 0x3f, 0x2c, 0xb8, 0xd3, 0x91, 0x65, 0x21, 0xb6, 0x92,
	0x93, 0x17, 0xb0, 0x27, 0x31, 0xc5, 0x4a, 0xea, 0xcb, 0xed, 0xcf, 0x1e, 0xb5, 0x42, 0x5d, 0xd3,
	0x3f, 0x5d, 0xf2, 0xf2, 0x7b, 0xb6, 0xfd, 0xba, 0xd4, 0x33, 0xb4, 0x9e, 0x8d, 0x9e, 0xc2, 0xb0,
	0x63, 0x90, 0x01, 0xf4, 0x3e, 0x2e, 0x5e, 0x2f, 0xce, 0x3e, 0x2f, 0x46, 0xb7, 0x54, 0xb1, 0x7c,
	0x49, 0x3f, 0x25, 0x8b, 0xf9, 0xc8, 0x22, 0x07, 0x30, 0x58, 0x9c, 0x7d, 0x58, 0x35, 0x82, 0x3d,
	0xfb, 0x6d, 0x81, 0xaf, 0x61, 0x51, 0x9e, 0x32, 0x72, 0x04, 0x83, 0x39, 0xc7, 0xd3, 0x2a, 0xcf,
	0xf5, 0x73, 0x18, 0xb6, 0xae, 0x93, 0xb0, 0xc9, 0xdf, 0xc8, 0xc9, 0x33, 0xe8, 0x37, 0xac, 0x49,
	0xd0, 0x32, 0x3b, 0x0b, 0x98, 0xb4, 0x9d, 0xee, 0x4a, 0x9f, 0xc0, 0xed, 0xa6, 0xf5, 0xf9, 0x95,
	0x7a, 0x97, 0x9d, 0xff, 0xc9, 0x1b, 0x26, 0x4f, 0xc1, 0xd3, 0x64, 0xc8, 0xe1, 0xbf, 0x88, 0x69,
	0xf0, 0x93, 0x07, 0x37, 0x03, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x56, 0xc8, 0xd0, 0x0d, 0x2d,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsReadClient is the client API for PostsRead service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsReadClient interface {
	GetFullPost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Post, error)
	GetPosts(ctx context.Context, in *GetPostsQuery, opts ...grpc.CallOption) (*MultiplePosts, error)
	GetPostsById(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*MultiplePosts, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type postsReadClient struct {
	cc *grpc.ClientConn
}

func NewPostsReadClient(cc *grpc.ClientConn) PostsReadClient {
	return &postsReadClient{cc}
}

func (c *postsReadClient) GetFullPost(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/postsread.PostsRead/GetFullPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsReadClient) GetPosts(ctx context.Context, in *GetPostsQuery, opts ...grpc.CallOption) (*MultiplePosts, error) {
	out := new(MultiplePosts)
	err := c.cc.Invoke(ctx, "/postsread.PostsRead/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsReadClient) GetPostsById(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*MultiplePosts, error) {
	out := new(MultiplePosts)
	err := c.cc.Invoke(ctx, "/postsread.PostsRead/GetPostsById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsReadClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/postsread.PostsRead/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsReadServer is the server API for PostsRead service.
type PostsReadServer interface {
	GetFullPost(context.Context, *Id) (*Post, error)
	GetPosts(context.Context, *GetPostsQuery) (*MultiplePosts, error)
	GetPostsById(context.Context, *Ids) (*MultiplePosts, error)
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedPostsReadServer can be embedded to have forward compatible implementations.
type UnimplementedPostsReadServer struct {
}

func (*UnimplementedPostsReadServer) GetFullPost(ctx context.Context, req *Id) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullPost not implemented")
}
func (*UnimplementedPostsReadServer) GetPosts(ctx context.Context, req *GetPostsQuery) (*MultiplePosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedPostsReadServer) GetPostsById(ctx context.Context, req *Ids) (*MultiplePosts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostsById not implemented")
}
func (*UnimplementedPostsReadServer) Check(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterPostsReadServer(s *grpc.Server, srv PostsReadServer) {
	s.RegisterService(&_PostsRead_serviceDesc, srv)
}

func _PostsRead_GetFullPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetFullPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postsread.PostsRead/GetFullPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetFullPost(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsRead_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postsread.PostsRead/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetPosts(ctx, req.(*GetPostsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsRead_GetPostsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).GetPostsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postsread.PostsRead/GetPostsById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).GetPostsById(ctx, req.(*Ids))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsRead_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsReadServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postsread.PostsRead/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsReadServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsRead_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postsread.PostsRead",
	HandlerType: (*PostsReadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullPost",
			Handler:    _PostsRead_GetFullPost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _PostsRead_GetPosts_Handler,
		},
		{
			MethodName: "GetPostsById",
			Handler:    _PostsRead_GetPostsById_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _PostsRead_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts-read.proto",
}
