version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "14000:14000"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    env_file:
      - config.env
    networks:
      - backend

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9200:9200"
    networks:
      - backend
    environment:
      - discovery.type=single-node

networks:
  backend:
