version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "14000:14000"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - DBOARD_SEARCH_ESINDEX=posts
      - DBOARD_SEARCH_ESADDR=http://elasticsearch:9200
      - DBOARD_SEARCH_LISTENPORT=14000
      - DBOARD_SEARCH_TLSCERT=certs/server.crt
      - DBOARD_SEARCH_TLSKEY=certs/server.key
      - DBOARD_SEARCH_TLSSERVERNAME=server
      - DBOARD_SEARCH_IPWHITELIST="127.0.0.1 ::1"
    networks:
      - backend

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9200:9200"
    networks:
      - backend
    environment:
      - discovery.type=single-node

networks:
  backend:
