version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "14000:14000"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - DBOARD_POSTSWRITE_ADDR=mysql:3306
      - DBOARD_POSTSWRITE_LISTENPORT=14000
      - DBOARD_POSTSWRITE_USERNAME=root
      - DBOARD_POSTSWRITE_PASSWORD=pass
      - DBOARD_POSTSWRITE_DBNAME=postswrite
      - DBOARD_POSTSWRITE_TLSCERT=certs/server.crt
      - DBOARD_POSTSWRITE_TLSKEY=certs/server.key
      - DBOARD_POSTSWRITE_TLSSERVERNAME=server
      - DBOARD_POSTSWRITE_IPWHITELIST=127.0.0.1 ::1      
    networks:
      - backend

  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=postswrite
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend: