// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts-write.proto

package postswrite

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (x *HealthCheckResponse_ServingStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HealthCheckResponse_ServingStatus_value, data, "HealthCheckResponse_ServingStatus")
	if err != nil {
		return err
	}
	*x = HealthCheckResponse_ServingStatus(value)
	return nil
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{11, 0}
}

type PostRequest struct {
	Title                *string  `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	Body                 *string  `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	UserId               *uint64  `protobuf:"varint,3,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{0}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PostRequest) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *PostRequest) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type PostId struct {
	PostId               *uint64  `protobuf:"varint,1,req,name=post_id,json=postId" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostId) Reset()         { *m = PostId{} }
func (m *PostId) String() string { return proto.CompactTextString(m) }
func (*PostId) ProtoMessage()    {}
func (*PostId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{1}
}

func (m *PostId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostId.Unmarshal(m, b)
}
func (m *PostId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostId.Marshal(b, m, deterministic)
}
func (m *PostId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostId.Merge(m, src)
}
func (m *PostId) XXX_Size() int {
	return xxx_messageInfo_PostId.Size(m)
}
func (m *PostId) XXX_DiscardUnknown() {
	xxx_messageInfo_PostId.DiscardUnknown(m)
}

var xxx_messageInfo_PostId proto.InternalMessageInfo

func (m *PostId) GetPostId() uint64 {
	if m != nil && m.PostId != nil {
		return *m.PostId
	}
	return 0
}

type DeletePostRequest struct {
	PostId               *uint64  `protobuf:"varint,1,req,name=post_id,json=postId" json:"post_id,omitempty"`
	UserId               *uint64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{2}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetPostId() uint64 {
	if m != nil && m.PostId != nil {
		return *m.PostId
	}
	return 0
}

func (m *DeletePostRequest) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type DeletePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{3}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

type SetLikes struct {
	Id                   *uint64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Likes                *int64   `protobuf:"varint,2,req,name=likes" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLikes) Reset()         { *m = SetLikes{} }
func (m *SetLikes) String() string { return proto.CompactTextString(m) }
func (*SetLikes) ProtoMessage()    {}
func (*SetLikes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{4}
}

func (m *SetLikes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLikes.Unmarshal(m, b)
}
func (m *SetLikes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLikes.Marshal(b, m, deterministic)
}
func (m *SetLikes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLikes.Merge(m, src)
}
func (m *SetLikes) XXX_Size() int {
	return xxx_messageInfo_SetLikes.Size(m)
}
func (m *SetLikes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLikes.DiscardUnknown(m)
}

var xxx_messageInfo_SetLikes proto.InternalMessageInfo

func (m *SetLikes) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SetLikes) GetLikes() int64 {
	if m != nil && m.Likes != nil {
		return *m.Likes
	}
	return 0
}

type SetLikesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLikesResponse) Reset()         { *m = SetLikesResponse{} }
func (m *SetLikesResponse) String() string { return proto.CompactTextString(m) }
func (*SetLikesResponse) ProtoMessage()    {}
func (*SetLikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{5}
}

func (m *SetLikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLikesResponse.Unmarshal(m, b)
}
func (m *SetLikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLikesResponse.Marshal(b, m, deterministic)
}
func (m *SetLikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLikesResponse.Merge(m, src)
}
func (m *SetLikesResponse) XXX_Size() int {
	return xxx_messageInfo_SetLikesResponse.Size(m)
}
func (m *SetLikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLikesResponse proto.InternalMessageInfo

type CommentRequest struct {
	PostId               *uint64  `protobuf:"varint,1,req,name=post_id,json=postId" json:"post_id,omitempty"`
	ParentId             *uint64  `protobuf:"varint,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	UserId               *uint64  `protobuf:"varint,3,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Body                 *string  `protobuf:"bytes,4,req,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRequest) Reset()         { *m = CommentRequest{} }
func (m *CommentRequest) String() string { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()    {}
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{6}
}

func (m *CommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRequest.Unmarshal(m, b)
}
func (m *CommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRequest.Marshal(b, m, deterministic)
}
func (m *CommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRequest.Merge(m, src)
}
func (m *CommentRequest) XXX_Size() int {
	return xxx_messageInfo_CommentRequest.Size(m)
}
func (m *CommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRequest proto.InternalMessageInfo

func (m *CommentRequest) GetPostId() uint64 {
	if m != nil && m.PostId != nil {
		return *m.PostId
	}
	return 0
}

func (m *CommentRequest) GetParentId() uint64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

func (m *CommentRequest) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CommentRequest) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type CreateCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{7}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

type ClearCommentRequest struct {
	CommentId            *uint64  `protobuf:"varint,1,req,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	UserId               *uint64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCommentRequest) Reset()         { *m = ClearCommentRequest{} }
func (m *ClearCommentRequest) String() string { return proto.CompactTextString(m) }
func (*ClearCommentRequest) ProtoMessage()    {}
func (*ClearCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{8}
}

func (m *ClearCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCommentRequest.Unmarshal(m, b)
}
func (m *ClearCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCommentRequest.Marshal(b, m, deterministic)
}
func (m *ClearCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCommentRequest.Merge(m, src)
}
func (m *ClearCommentRequest) XXX_Size() int {
	return xxx_messageInfo_ClearCommentRequest.Size(m)
}
func (m *ClearCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCommentRequest proto.InternalMessageInfo

func (m *ClearCommentRequest) GetCommentId() uint64 {
	if m != nil && m.CommentId != nil {
		return *m.CommentId
	}
	return 0
}

func (m *ClearCommentRequest) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type ClearCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearCommentResponse) Reset()         { *m = ClearCommentResponse{} }
func (m *ClearCommentResponse) String() string { return proto.CompactTextString(m) }
func (*ClearCommentResponse) ProtoMessage()    {}
func (*ClearCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{9}
}

func (m *ClearCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCommentResponse.Unmarshal(m, b)
}
func (m *ClearCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCommentResponse.Marshal(b, m, deterministic)
}
func (m *ClearCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCommentResponse.Merge(m, src)
}
func (m *ClearCommentResponse) XXX_Size() int {
	return xxx_messageInfo_ClearCommentResponse.Size(m)
}
func (m *ClearCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCommentResponse proto.InternalMessageInfo

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{10}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	Status               *HealthCheckResponse_ServingStatus `protobuf:"varint,1,req,name=status,enum=postswrite.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f896a35be189e2, []int{11}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("postswrite.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*PostRequest)(nil), "postswrite.PostRequest")
	proto.RegisterType((*PostId)(nil), "postswrite.PostId")
	proto.RegisterType((*DeletePostRequest)(nil), "postswrite.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "postswrite.DeletePostResponse")
	proto.RegisterType((*SetLikes)(nil), "postswrite.SetLikes")
	proto.RegisterType((*SetLikesResponse)(nil), "postswrite.SetLikesResponse")
	proto.RegisterType((*CommentRequest)(nil), "postswrite.CommentRequest")
	proto.RegisterType((*CreateCommentResponse)(nil), "postswrite.CreateCommentResponse")
	proto.RegisterType((*ClearCommentRequest)(nil), "postswrite.ClearCommentRequest")
	proto.RegisterType((*ClearCommentResponse)(nil), "postswrite.ClearCommentResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "postswrite.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "postswrite.HealthCheckResponse")
}

func init() { proto.RegisterFile("posts-write.proto", fileDescriptor_e0f896a35be189e2) }

var fileDescriptor_e0f896a35be189e2 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x51, 0x53, 0xd3, 0x40,
	0x10, 0x36, 0xa1, 0x14, 0xba, 0x85, 0x52, 0x96, 0x68, 0x3b, 0x51, 0xa0, 0xe4, 0x89, 0x17, 0x3a,
	0x0e, 0x6f, 0xfa, 0x68, 0xed, 0x48, 0x07, 0x0d, 0x98, 0xa8, 0x3c, 0x32, 0x91, 0xec, 0x48, 0x86,
	0xd0, 0xc4, 0xdc, 0x55, 0xc7, 0xff, 0xe0, 0x0f, 0xf0, 0xe7, 0x3a, 0x77, 0x97, 0x26, 0x77, 0xd0,
	0xda, 0x19, 0xdf, 0xb2, 0xdf, 0x7e, 0xbb, 0xdf, 0x77, 0x9b, 0x0f, 0x76, 0xf3, 0x8c, 0x71, 0x76,
	0xf2, 0xb3, 0x48, 0x38, 0x0d, 0xf3, 0x22, 0xe3, 0x19, 0x82, 0x84, 0x24, 0xe2, 0x5d, 0x42, 0xfb,
	0x32, 0x63, 0x3c, 0xa0, 0xef, 0x33, 0x62, 0x1c, 0x1d, 0x58, 0xe7, 0x09, 0x4f, 0xa9, 0x6f, 0x0d,
	0xec, 0xe3, 0x56, 0xa0, 0x0a, 0x44, 0x68, 0x7c, 0xcd, 0xe2, 0x5f, 0x7d, 0x5b, 0x82, 0xf2, 0x1b,
	0x7b, 0xb0, 0x31, 0x63, 0x54, 0x5c, 0x27, 0x71, 0x7f, 0x6d, 0x60, 0x1f, 0x37, 0x82, 0xa6, 0x28,
	0x27, 0xb1, 0x77, 0x04, 0x4d, 0xb1, 0x71, 0x12, 0x0b, 0x8a, 0x50, 0x12, 0x14, 0x4b, 0x51, 0x72,
	0xd9, 0xf0, 0xc6, 0xb0, 0xfb, 0x96, 0x52, 0xe2, 0xa4, 0x4b, 0x2f, 0x63, 0xeb, 0x4a, 0xf6, 0xc0,
	0xd2, 0x94, 0x1c, 0x40, 0x7d, 0x0d, 0xcb, 0xb3, 0x29, 0x23, 0xef, 0x25, 0x6c, 0x86, 0xc4, 0xdf,
	0x27, 0x77, 0xc4, 0xb0, 0x03, 0x76, 0xb5, 0xce, 0x4e, 0x62, 0xf1, 0xbc, 0x54, 0x34, 0xe4, 0x4b,
	0xd6, 0x02, 0x55, 0x78, 0x08, 0xdd, 0xf9, 0x44, 0xb5, 0x85, 0x41, 0x67, 0x94, 0xdd, 0xdf, 0xd3,
	0x74, 0xb5, 0xbf, 0xe7, 0xd0, 0xca, 0xa3, 0x82, 0xa6, 0xbc, 0x76, 0xb8, 0xa9, 0x00, 0xd3, 0xbc,
	0x71, 0xa6, 0xea, 0xa6, 0x8d, 0xfa, 0xa6, 0x5e, 0x0f, 0x9e, 0x8e, 0x0a, 0x8a, 0x38, 0x55, 0xd2,
	0xa5, 0x9b, 0x0f, 0xb0, 0x37, 0x4a, 0x29, 0x2a, 0x1e, 0x58, 0xda, 0x07, 0xb8, 0x51, 0x48, 0xed,
	0xaa, 0x55, 0x22, 0xff, 0x3a, 0xdc, 0x33, 0x70, 0xcc, 0x75, 0xa5, 0x8c, 0x03, 0x78, 0x46, 0x51,
	0xca, 0x6f, 0x47, 0xb7, 0x74, 0x73, 0x57, 0xaa, 0x78, 0x7f, 0x2c, 0xd8, 0x33, 0x60, 0xc5, 0xc6,
	0x31, 0x34, 0x19, 0x8f, 0xf8, 0x8c, 0x49, 0xe5, 0xce, 0xe9, 0xc9, 0xb0, 0xce, 0xd5, 0x70, 0xc1,
	0xc0, 0x30, 0xa4, 0xe2, 0x47, 0x32, 0xfd, 0x16, 0xca, 0xa1, 0xa0, 0x1c, 0xf6, 0x5e, 0xc3, 0xb6,
	0xd1, 0xc0, 0x36, 0x6c, 0x7c, 0xf6, 0xcf, 0xfd, 0x8b, 0x2b, 0xbf, 0xfb, 0x44, 0x14, 0xe1, 0x38,
	0xf8, 0x32, 0xf1, 0xdf, 0x75, 0x2d, 0xdc, 0x81, 0xb6, 0x7f, 0xf1, 0xe9, 0x7a, 0x0e, 0xd8, 0xa7,
	0xbf, 0x1b, 0x00, 0xe2, 0xe7, 0xb3, 0x2b, 0x21, 0x8a, 0xaf, 0x00, 0xd4, 0xfd, 0x04, 0x86, 0x3d,
	0xdd, 0x8f, 0x96, 0x34, 0x17, 0x1f, 0x36, 0x26, 0x31, 0x9e, 0x03, 0xd4, 0x59, 0xc2, 0x7d, 0x9d,
	0xf1, 0x28, 0xaa, 0xee, 0xc1, 0xb2, 0x76, 0x79, 0x99, 0x37, 0xb0, 0x15, 0x12, 0x17, 0x90, 0x8a,
	0xa1, 0xa3, 0xf3, 0xe7, 0x51, 0x73, 0x5f, 0x2c, 0x42, 0xab, 0x1d, 0x3e, 0x6c, 0x1b, 0x59, 0x40,
	0x57, 0xa7, 0x9b, 0x41, 0x70, 0x8f, 0x8c, 0xde, 0xa2, 0x08, 0xe1, 0x47, 0xd8, 0xd2, 0xff, 0x39,
	0x1e, 0x1a, 0x23, 0x8f, 0xc3, 0xe5, 0x0e, 0x96, 0x13, 0xaa, 0x00, 0xec, 0x84, 0xc4, 0x4b, 0xf4,
	0xff, 0x5f, 0x7a, 0x06, 0xeb, 0x32, 0x27, 0x78, 0xb0, 0x34, 0x40, 0xca, 0xd1, 0xe1, 0x8a, 0x80,
	0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xc4, 0x16, 0x2e, 0xec, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsWriteClient is the client API for PostsWrite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsWriteClient interface {
	CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostId, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	SetPostLikes(ctx context.Context, in *SetLikes, opts ...grpc.CallOption) (*SetLikesResponse, error)
	CreateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	ClearComment(ctx context.Context, in *ClearCommentRequest, opts ...grpc.CallOption) (*ClearCommentResponse, error)
	SetCommentLikes(ctx context.Context, in *SetLikes, opts ...grpc.CallOption) (*SetLikesResponse, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type postsWriteClient struct {
	cc *grpc.ClientConn
}

func NewPostsWriteClient(cc *grpc.ClientConn) PostsWriteClient {
	return &postsWriteClient{cc}
}

func (c *postsWriteClient) CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostId, error) {
	out := new(PostId)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) SetPostLikes(ctx context.Context, in *SetLikes, opts ...grpc.CallOption) (*SetLikesResponse, error) {
	out := new(SetLikesResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/SetPostLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) CreateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) ClearComment(ctx context.Context, in *ClearCommentRequest, opts ...grpc.CallOption) (*ClearCommentResponse, error) {
	out := new(ClearCommentResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/ClearComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) SetCommentLikes(ctx context.Context, in *SetLikes, opts ...grpc.CallOption) (*SetLikesResponse, error) {
	out := new(SetLikesResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/SetCommentLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsWriteClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/postswrite.PostsWrite/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsWriteServer is the server API for PostsWrite service.
type PostsWriteServer interface {
	CreatePost(context.Context, *PostRequest) (*PostId, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	SetPostLikes(context.Context, *SetLikes) (*SetLikesResponse, error)
	CreateComment(context.Context, *CommentRequest) (*CreateCommentResponse, error)
	ClearComment(context.Context, *ClearCommentRequest) (*ClearCommentResponse, error)
	SetCommentLikes(context.Context, *SetLikes) (*SetLikesResponse, error)
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedPostsWriteServer can be embedded to have forward compatible implementations.
type UnimplementedPostsWriteServer struct {
}

func (*UnimplementedPostsWriteServer) CreatePost(ctx context.Context, req *PostRequest) (*PostId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostsWriteServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedPostsWriteServer) SetPostLikes(ctx context.Context, req *SetLikes) (*SetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPostLikes not implemented")
}
func (*UnimplementedPostsWriteServer) CreateComment(ctx context.Context, req *CommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedPostsWriteServer) ClearComment(ctx context.Context, req *ClearCommentRequest) (*ClearCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearComment not implemented")
}
func (*UnimplementedPostsWriteServer) SetCommentLikes(ctx context.Context, req *SetLikes) (*SetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCommentLikes not implemented")
}
func (*UnimplementedPostsWriteServer) Check(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterPostsWriteServer(s *grpc.Server, srv PostsWriteServer) {
	s.RegisterService(&_PostsWrite_serviceDesc, srv)
}

func _PostsWrite_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).CreatePost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_SetPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLikes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).SetPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/SetPostLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).SetPostLikes(ctx, req.(*SetLikes))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).CreateComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_ClearComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).ClearComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/ClearComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).ClearComment(ctx, req.(*ClearCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_SetCommentLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLikes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).SetCommentLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/SetCommentLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).SetCommentLikes(ctx, req.(*SetLikes))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsWrite_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsWriteServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postswrite.PostsWrite/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsWriteServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsWrite_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postswrite.PostsWrite",
	HandlerType: (*PostsWriteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostsWrite_CreatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostsWrite_DeletePost_Handler,
		},
		{
			MethodName: "SetPostLikes",
			Handler:    _PostsWrite_SetPostLikes_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostsWrite_CreateComment_Handler,
		},
		{
			MethodName: "ClearComment",
			Handler:    _PostsWrite_ClearComment_Handler,
		},
		{
			MethodName: "SetCommentLikes",
			Handler:    _PostsWrite_SetCommentLikes_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _PostsWrite_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts-write.proto",
}
