version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "14000:14000"
    restart: unless-stopped
    depends_on:
      - minio
    env_file:
      - config.env
    networks:
      - backend

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    env_file:
      - ./minio/minio.env
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes: 
      - data:/data
    command: server /export

networks:
  backend:

volumes:
  data: