version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "14000:14000"
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      - DBOARD_MEDIA_ENDPOINT=minio:9000
      - DBOARD_MEDIA_LISTENPORT=14000
      - DBOARD_MEDIA_ACCESSKEYID=AKIAIOSFODNN7EXAMPLE
      - DBOARD_MEDIA_SECRETACCESSKEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - DBOARD_MEDIA_USESSL=false
      - DBOARD_MEDIA_BUCKETNAME=media
      - DBOARD_MEDIA_TLSCERT=certs/server.crt
      - DBOARD_MEDIA_TLSKEY=certs/server.key
      - DBOARD_MEDIA_TLSSERVERNAME=server
      - DBOARD_MEDIA_IPWHITELIST=127.0.0.1 ::1
    networks:
      - backend

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes: 
      - data:/data
    command: server /export

networks:
  backend:

volumes:
  data: